services:
  ollama:
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_GPU_LAYERS=35
    ports:
      - "11434:11434"
    volumes:
      - /eniac/autodev/models/ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 20s
      timeout: 10s
      retries: 3

  qdrant:
    image: qdrant/qdrant
    environment:
      - QDRANT__CLUSTER__ENABLED=false  
      - QDRANT__STORAGE__HANDLE_COLLECTION_LOAD_ERRORS=true
      - QDRANT__SERVICE__HTTP_PORT=6333
    ports:
      - "6334:6333"  # Changed port to avoid conflict
    volumes:
      - /eniac/autodev/qdrant_live/storage:/qdrant/storage
      - /eniac/autodev/qdrant_live/snapshots:/qdrant/snapshots
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/readyz"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 60s
    user: "1000:1000"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - /eniac/autodev/redis:/data
    command: redis-server --appendonly yes
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - /eniac/autodev/n8n:/home/node/.n8n
    environment:
      - N8N_RUNNERS_ENABLED=true
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_USER_FOLDER=/home/node/.n8n
      - N8N_SECURE_COOKIE=False
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    user: "1000:1000"
    depends_on:
      redis:
        condition: service_healthy
