services:
  ollama:
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_GPU_LAYERS=35
    ports:
      - "11434:11434"
    volumes:
      - ${MODELS_PATH}/ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 20s
      timeout: 10s
      retries: 3

  qdrant:
    image: qdrant/qdrant
    environment:
      - QDRANT__CLUSTER__ENABLED=false
      - QDRANT__STORAGE__HANDLE_COLLECTION_LOAD_ERRORS=true
    ports:
      - "6333:6333"
    volumes:
      - ${QDRANT_PATH}/storage:/qdrant/storage
      - ${QDRANT_PATH}/snapshots:/qdrant/snapshots
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/readyz"]
      interval: 20s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ${REDIS_PATH}:/data
    command: redis-server --appendonly yes
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ${N8N_PATH}:/home/node/.n8n
    environment:
      - N8N_RUNNERS_ENABLED=true
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_USER_FOLDER=/home/node/.n8n
      - N8N_SECURE_COOKIE=false
    user: "1000:1000"
    depends_on:
      redis:
        condition: service_healthy
