services:
  app:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
      target: dev
    ports:
      - "8000:8000"
      - "5555:5555"
    volumes:
      - ../..:/app
      - /eniac/autodev/artifacts:/app/artifacts
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=http://ollama:11434
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      ollama:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      redis:
        condition: service_healthy
